spring:
  application:
    name: service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 382194553074-j1d2kvk4eqet33ms658dogqbole6v64g.apps.googleusercontent.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 18181
  servlet:
    context-path: /gallery

upload:
  application-home: true
  directory: uploads
  subdirectory-pattern: "^(.{4})(.{2})(.{2}).*$"
  whitelist:
    - image/bmp
    - image/gif
    - image/jpeg
    - image/pjpeg
    - image/png
    - image/tiff
  filename:
    format: "%1$s-%2$d.%3$s"
    randomizer-limit: 1000000
    timestamp:
      format: yyyyMMddHHmmssSSS
      time-zone: UTC

